### ISSUE TITLE
recaptcha__en.js:58 Uncaught (in promise) Error: reCAPTCHA placeholder element must be an element or id

### ISSUE THREAD

**Issue by vijaygarg-ahead** [google/recaptcha#376] opened 2020-04-30 13:22 UTC
**Issue description**
I am using MooTools on my website and I am facing this issue "recaptcha__en.js:58 Uncaught (in promise) Error: reCAPTCHA placeholder element must be an element or id".

The below error is showing:

recaptcha__en.js:58 Uncaught (in promise) Error: reCAPTCHA placeholder element must be an element or id
    at mv (recaptcha__en.js:58)
    at Object.render (mootools-core-1.4.5-full-compat-nc.js?c=2:959)
    at core.js?c=2:952
    at Elements.Elements.forEach (<anonymous>)
    at Function.forEach (mootools-core-1.4.5-full-compat-nc.js?c=2:220)
    at Elements.Elements.each (mootools-core-1.4.5-full-compat-nc.js?c=2:337)
    at Object.render (core.js?c=2:947)

**Comment by DJB31st** [comment] 2020-04-30 15:25
Looks to be a duplicate of this https://github.com/google/recaptcha/issues/374 (albeit with a different error)

**Closed** 2023-02-20 12:09 UTC
Labels: duplicate, widget
