### ISSUE TITLE
Request timing out

### ISSUE THREAD

**Issue by jordanbrierley** [google/recaptcha#193] opened 2017-08-31 13:13 UTC
Do you know if google has blocked any requests from using file_get_contents (Line 68: [recaptcha/src/ReCaptcha/RequestMethod/Post.php](https://github.com/google/recaptcha/blob/master/src/ReCaptcha/RequestMethod/Post.php)) ?

When I've tested using cURL I can request the url fine but when it seems to have a problem with file_get_contents(), it's the same when I try and do a similar query using either `file_get_contents`
or `simplexml_load_file` for the Geocode API which leads me to believe Google may have blocked it (eg. https://maps.googleapis.com/maps/api/geocode/json?address=London) as oppose to cURL which works fine?

**Comment by lengyuan** [comment] 2017-09-07 13:16
Got the same issue with file_get_contents

**Comment by hamzabas** [comment] 2017-09-28 10:38
What PHP version are you using?

**Comment by lengyuan** [comment] 2017-09-28 10:41
Hi hamzabas

Sorry I forgot to update. It turns out the issue was caused by IPv6. We are not sure why, but DNS returns IP v6 instead of IP v4 address of google.com, which causes time out. 

The issue was fixed by disabling IP v6 function of server.

**Comment by hamzabas** [comment] 2017-09-28 10:48
Ah Okay I thought that the problem is caused by the [openSSL changes in PHP 5.6.x](http://php.net/manual/en/migration56.openssl.php)

**Comment by rowan-m** [comment] 2018-07-29 21:08
Closing super old issues. Please re-raise if still relevant.

**Closed by rowan-m** 2018-07-29 21:08 UTC
