### ISSUE TITLE
Uncaught (in promise) Timeout recaptcha__en.js

### ISSUE THREAD

**Issue by atulshrma91** [google/recaptcha#269] opened 2018-10-03 21:39 UTC
Google captcha is working well but console show up the error after some time

**Comment by rowan-m** [comment] 2018-10-03 22:51
Would you be able to provide a bit more information about how to reproduce this, please. Preferably a URL and instructions for what to do to see this error in the console.

**Comment by atulshrma91** [comment] 2018-10-04 07:14
Sorry I'm using react captcha and I opened the issue on wrong repository. 

You can delete the issue. Thank you for your time

**Comment by subvertallchris** [comment] 2018-10-15 15:11
I can provide a partial stacktrace of this. Comes from production so it's mangled, though. :-(

```
Uncaught (in promise) timeout

setTimeout (async)
p @ recaptcha__en.js:99
(anonymous) @ recaptcha__en.js:306
CW @ recaptcha__en.js:306
Os @ recaptcha__en.js:482
(anonymous) @ recaptcha__en.js:484
Promise.catch (async)
Os @ recaptcha__en.js:483
ss @ recaptcha__en.js:489
qY.PN @ recaptcha__en.js:486
re @ recaptcha__en.js:490
t.reset @ main.8d559850.js:16
t.componentWillUnmount @ main.8d559850.js:16
Ho @ main.8d559850.js:73
Yo @ main.8d559850.js:73
$a @ main.8d559850.js:73
Xa @ main.8d559850.js:73
Ga @ main.8d559850.js:73
Qa @ main.8d559850.js:73
ts @ main.8d559850.js:73
Ln @ main.8d559850.js:73
```

In my case, it happens after the unmount of a React component that was presenting a recaptcha. It has been occurring consistently for a few months.

**Comment by fluffy-samurai** [comment] 2018-10-23 16:34
react-google-recaptcha claims this issue live in here. It seems to be related to when the recaptcha is unmounted, at an undetermined time later, a timeout error occurs in the browser.

**Comment by TomPradat** [comment] 2018-10-31 16:21
Maybe there is a step missing in react-google-recaptcha when removing the widget. Here are the steps done to remove the widget properly : 
- Removing all nodes from the container use in the grecaptcha.render method
- Use grecaptcha.reset to reset the widget

So the problem is that you get Uncaught (in promise) timeout after some time after removing the widget. If the steps above are correct then the problem is probably due to recaptcha

**Comment by hartzis** [comment] 2018-10-31 20:45
@TomPradat does the widget itself still need to be in the dom/exist when reset is called?

**Comment by pleinonen** [comment] 2018-11-01 06:20
Also reproducible in Angular 6 when component hosting the recaptcha widget is destroyed after successful recaptcha check.

**Comment by Goaty89** [comment] 2018-11-01 07:21
Yeah, it causing a lot fault alarm..Please fix.

**Comment by TomPradat** [comment] 2018-11-01 09:47
> @TomPradat does the widget itself still need to be in the dom/exist when reset is called?

I wondered about that so i forked and try to call reset before unmounting from the dom but i still got the issue

**Comment by sdet-ro** [comment] 2018-11-15 10:49
I am also reproducing this, in a blade template in composition with Vue.

  ```
| setTimeout (async) |   |  
-- | -- | -- | --
  | M | @ | recaptcha__en.js:105
  | (anonymous) | @ | recaptcha__en.js:319
  | G4 | @ | recaptcha__en.js:13
  | next | @ | recaptcha__en.js:12
  | (anonymous) | @ | recaptcha__en.js:12
  | ig | @ | recaptcha__en.js:12
  | Xe | @ | recaptcha__en.js:13
  | Qa.send | @ | recaptcha__en.js:319
  | gV | @ | recaptcha__en.js:329
  | (anonymous) | @ | recaptcha__en.js:350
  | (anonymous) | @ | anchor:197

```

**Comment by patelnav** [comment] 2019-03-06 09:06
Any update on this?
@rowan-m  If you require more information on this bug, do let us know.

**Comment by praneetloke** [comment] 2019-03-12 18:02
I encountered this with an Angular app. There was a detail in the examples on the reCAPTCHA v2 docs page, that I just found. In one of the examples, you can see that they are capturing the result of the call to `widget = ...render()` and then whenever the form is submitted, they are calling `reset()` by passing to it the result of the `render()` call. I replicated this with my app and it worked. I no longer get the timeout console errors. It seems that just calling `reset()` without passing any parameters isn't actually reset the "default" widget as the docs state.

This is what I did, and so far it seems to be working without throwing the timeout error:

```typescript
// This code is in TypeScript.
private renderedWidget: any;

// In some function, I call the render() on the global grecaptcha object.
this.rendered = window.grecaptcha.render(...);

/** 
* Later, after doing my async request, I reset the captcha like this for both success and failure scenarios.
* You can also call this when your component is unloaded/destroyed.
* If your component isn't unloaded after using the reCAPTCHA response 
* until the timeout period, you may receive the timeout
* error, so you should reset the widget as early as possible.
*/

...
window.grecaptcha.reset(this.rendered);
...
```

**Comment by pleinonen** [comment] 2019-03-13 05:37
Yeah, it takes a while before error appear, maybe 15-30 seconds or so. Maybe some internal timeout or something is triggered? Anyway, only 'fix' I could come up with is to reload the page, which sucks.

**Comment by praneetloke** [comment] 2019-03-13 17:53
I think I have another solution, though, it may be specific to Angular. I made a few observations since my last comment above and think I have a fairly stable solution now.

- The `Uncaught (in promise): Timeout` comes from `zone.js`. This makes it seem that there is an unhandled promise timeout, which `zone.js` is bubbling-up.
- Resetting the widget after using the response token is the right thing to do. However, doing so seems to be producing another error `n is null` sporadically along with the promise timeout error.

So I made two changes:

- Run all functions of `grecaptcha` using `NgZone`'s `runOutsideAngular()`, which prevents any errors from recaptcha bubbling-up to the main app itself. For example,

```typescript
// Sample for an Angular app.
...
constructor(private zone: NgZone){}
...
...
this.zone.runOutsideAngular(() => window.recaptcha.render(...));
...
```
- Call the `reset()` function outside any HTTP client subscriptions. That is, don't call `reset()` from within any RxJS subscriptions. (I forget the reason why I had to do this, but it was due to some weird errors)

With the above two changes, I believe I have the widget working in a stable manner in an Angular app. I believe you could apply similar semantics to a React or Vue app as well.

I do have to admit that not having access to the un-minified source for the JS client made things very difficult. I spent way too much time identifying traffic lights, crosswalks, and fire hydrants trying to get confirm that my changes made a difference. On top of that, **this repo** appears to only talk about the PHP client, and makes no mention of the JS client. I searched for a different repo that would have the JS client, but couldn't find one.

**Comment by JustFly1984** [comment] 2019-03-14 18:20
I also have same error on unmounting component in react.js app.

**Comment by blindfish3** [comment] 2019-04-01 15:15
I also encountered this; though from my tests it's happening when the iframe URL fails to load.  I can reproduce by blocking network requests to: `https://www.google.com/recaptcha/api2/anchor?*` and waiting for the timeout.

I've just hit on a possible approach to handling the error: in the `ready` event, make an explicit call to `execute` and wrap this in a try/catch.  I'm assuming that the library attempts to call execute internally on load and does nothing to handle timeout errors.

It would be nice not to have to hack around this issue - e.g. provide a timeout or error callback...

**Comment by erwin-k** [comment] 2019-07-17 11:30
I'm using React and also encountered this error, however, I managed to fix it. (reCAPTCHA v2)
I simply passed the render function to grecaptcha.ready() and did not use the onload param in the script url like the docs tell you to. This fixed the timeout error and forever loading spinner for me.
```javascript
componentDidMount () {

  grecaptcha.ready(() => {
    grecaptcha.render('g-recaptcha', { sitekey: 'xxx' })
  })
}
```

**Comment by JustFly1984** [comment] 2019-10-03 15:24
The issue is still there

**Comment by Code42Cate** [comment] 2019-10-07 22:02
Same here with plain JavaScript. Trying to remove the widget as @TomPradat said, getting the timeout after 15-30 Seconds :(

**Comment by JustFly1984** [comment] 2019-10-08 00:05
I have get rid of recaptcha in all of my projects. Too much problems, and it seems it will break soon for everybody, since there is new requirements for http headers from new chrome

**Comment by computerwizjared** [comment] 2019-10-11 05:28
Hi all, I figured out the issue with Angular today. It seems that because Angular replaces the body of the document with its own content, it actually removes the recaptcha badge from the page. This badge is required for recaptcha to function properly, although it can be set to `visibility: hidden;` in CSS (just not `display: none;`).

My solution is in my Angular app's `main.ts` file, I added this to run after Angular's bootstrap:
```
platformBrowserDynamic().bootstrapModule( AppModule ).then(() => {
  // due to some issues with how recaptcha and angular interact,
  // we have to load the recaptcha script after angular bootstraps
  let node = document.createElement('script');
  node.src = 'https://www.google.com/recaptcha/api.js?render=YOUR_SITE_KEY';
  node.async = true;
  node.defer = true;
  document.getElementsByTagName('head')[0].appendChild(node);
}
```
This ensures that the script is loaded after the page has loaded completely and Angular has finished initializing everything.

**Comment by j-mew-s** [comment] 2019-12-03 11:54
We have seen this error too. The user reported that they left our SPA (React) open overnight (laptop hibernating) and in the morning they could not log in until they restarted their browser, though we (and they) have been unable to replicate it. Logs show them hitting this error on each login attempt.

We load the script once (`<script src='...'>`) for the lifetime of the SPA, and call `execute()` for each login attempt.

I notice a couple of react/grecaptcha npm packages inject via Javascript and wondered whether it that might avoid badge issues @computerwizjared mentioned hitting in Angular. However, it looks like react-google-recaptcha suffers anyway (https://github.com/dozoisch/react-google-recaptcha/issues/103) so maybe that wouldn't make any difference.

**Comment by Gonusi** [comment] 2020-01-24 07:35
I also experience the same issue on my react app. After calling `grecaptcha.execute` I reset the recaptcha using `grecaptcha.reset(widgetId)`. After arount 15 seconds, I get a timeout error:

`
cba234a7ec519249734c915860aed8cf10d4afd615bd91f8dc88e71b547e2d2cd2aff1755aa01f7f:1 Uncaught (in promise) Timeout (h)
setTimeout (async)
f @ recaptcha__lt.js:115
(anonymous) @ recaptcha__lt.js:364
Mn @ recaptcha__lt.js:19
next @ recaptcha__lt.js:18
(anonymous) @ recaptcha__lt.js:19
EP @ recaptcha__lt.js:19
cx @ recaptcha__lt.js:18
Ww.send @ recaptcha__lt.js:364
(anonymous) @ recaptcha__lt.js:520
Promise.then (async)
V.bZ @ recaptcha__lt.js:520
a.H @ recaptcha__lt.js:365
(anonymous) @ recaptcha__lt.js:365
Mn @ recaptcha__lt.js:19
next @ recaptcha__lt.js:18
O @ recaptcha__lt.js:19
Promise.then (async)
Y @ recaptcha__lt.js:19
(anonymous) @ recaptcha__lt.js:19
EP @ recaptcha__lt.js:19
cx @ recaptcha__lt.js:18
Ww @ recaptcha__lt.js:364
(anonymous) @ recaptcha__lt.js:363
$6 @ recaptcha__lt.js:100
uz @ recaptcha__lt.js:99
KP.O @ recaptcha__lt.js:99
Show 24 more blackboxed frames
`

**Comment by gapipro** [comment] 2020-01-29 15:54
I think I solved it:
When you destroy Recaptcha component in your preferred JS framework, make sure you set 
`window.grecaptcha = null`
`window.recaptcha = null`

After this you shouldn't see timeout error anymore.

**Comment by JFGHT** [comment] 2020-01-30 09:03
> `window.grecaptcha = null`
> `window.recaptcha = null`

No, this doesn't solve the error.

**Comment by gapipro** [comment] 2020-01-30 10:19
Additional thing to do is 
`document.querySelectorAll(‘iframe[src*=recaptcha]’).forEach(a => a.remove())`

**Comment by Kipperlenny** [comment] 2020-01-30 10:42
Same "problem" (working well, but error in console) with Divi WordPress Theme and recaptcha V3.

**Comment by rudral** [comment] 2020-01-30 23:24
I also encountered the same error in my **react app** while integrating the **firebase**'s _phone authentication_.

Finally I tried the code below, but unfortunately same error continues to exist... ( I also removed the container element of the recaptcha from the virtual dom of react )

```javascript
window.recaptchaVerifier.reset();
window.recaptchaVerifier.clear();
window.recaptchaVerifier = null;
```

**Comment by MixLog2016** [comment] 2020-03-06 15:20
I solved my error by calling `grecaptcha.execute` only when submiting a form . 
I have an AngularJS app and i included the script inside index.html

`
<script src="https://www.google.com/recaptcha/api.js?render=YOUR_SITE_KEY"></script>
`

after doing so i used ng-click on a button on another html page and on the controller i wrote the function below 
`function _registerNewUser() {
            grecaptcha.ready(function () {
                grecaptcha.execute('YOUR_SITE_KEY', { action: 'register' }).then(function (token) {

                    $http.post(serviceBase + 'api/Google', { GoogleToken: token }).then(function (response) {
                        ............
                        
                    }, function (response) {
                        .........
                    });
//the function above is to verify the user's token on the Back End with .NET
                });
            });
        }`

**Comment by ErraticFox** [comment] 2020-03-27 21:15
Can we *please* get a fix for this? We've been working on a fix before this post and tbh, after coming back two years later and it *still* not fixed is quite saddening :( 
https://github.com/DethAriel/ng-recaptcha/issues/123

The repo owner of the link even describes and also says it resides in an unsolved promise in `recaptcha__en.js`, any update?

**Comment by ANTOSzbk** [comment] 2020-03-31 19:51
I also had this console warning when debugging without server-side verification (call to Google API to verify if reCAPTCHA client response is valid). My implementation includes dynamically created element for every captcha necessary and is in plain JS so everyone can refer to. In my case `app` url is address of Node.js application for server-side verification. 
https://gist.github.com/ANTOSzbk/75ed7003e914162550f61399122a3bd4

**Comment by ArmandoAssuncao** [comment] 2020-07-07 21:49
Some update?

**Comment by RamonSalem** [comment] 2020-08-24 23:29
Some update 2?

**Comment by invisor** [comment] 2020-09-21 13:55
Some update 3?

**Comment by stuartpearman** [comment] 2020-09-28 21:25
I wasn't using a frontend framework here, but was running into this with v3.

I was able to fix the issue on my end by wrapping all my views within the body:

```html
<div class="app-viewport">
    <!-- everything the user sees -->
</div>
```

Then made sure to perform any DOM manipulation on that div instead of on the body element.

The recaptcha badge really doesn't like to be rebuilt it seems!

**Comment by matiasgarcia** [comment] 2021-02-05 20:01
Some update on this?

**Comment by Landen13** [comment] 2021-02-22 14:19
Any update?

**Comment by willvlad** [comment] 2021-03-08 14:47
it's almost 3 years! Is anyone from google working on a fix for this?

**Comment by fxck** [comment] 2021-03-11 11:33
I wonder what could possibly be the top most upvoted issue in this repository.. 🤔

**Comment by fgfl** [comment] 2021-03-12 17:46
Here's the work around I implemented in case it can help anyone. The general idea is to remove the grecaptcha script element and any of the elements the script appends to the DOM, then re-append the grecaptcha script so that it can re-run and set everything back up without having to refresh the app/webpage.

1. when the grecaptcha script times out, remove all the elements related to grecaptcha. This step is not important, but it keeps the DOM clean and removes the timeout message.
  - remove the script tag before the grecaptcha script element to clean up the DOM. This is a script grecaptcha appends to the DOM when it runs.
  - remove the `div` containing the grecaptcha timeout text to hide the message. Just search for a `div` containing the text.
  - remove any grecaptcha badges still in the DOM. Query for elements with the `grecaptcha-badge` class.
  - remove grecaptcha script (easy if you set an id on the element initially and query for the element)
2. Set the global `grecaptcha` variable to `null` or `undefined`
  - **this is important!** I found that if `grecaptcha` is already defined, then the grecaptcha script will not append the script it downloads nor the badge that makes grecaptcha work
3. created the below script element as per the docs and append it to the DOM to make it run.
`<script src="https://www.google.com/recaptcha/api.js?render=reCAPTCHA_site_key"></script>`
4. Once the script appends the downloaded script and the grecaptcha badge back to the DOM, call `grecaptch.execute` whenever you need to use grecaptcha. You should be able to check with `grecaptcha.ready`.

**Comment by BryantIT** [comment] 2021-03-22 10:08
So one thing I noticed, I only get this error if the catpcha is outside a form tag.  When placed inside a form tag and .excute is called with the submit button I do not get this error.

**Comment by fumiyakk** [comment] 2021-03-23 04:43
@BryantIT Thanks!
As you said, I put the capture and formfields in one form tag. And no timeout error has occurred.

**Comment by willvlad** [comment] 2021-04-16 21:28
What makes no sense is that if it's an invisible captcha, why does it pop up for the user to do it? 

Anyone knows how to make it a really invisible captcha?

**Comment by infodusha** [comment] 2022-04-17 21:09
Any updates on that in 2022?

**Comment by Beraa995** [comment] 2022-05-10 22:21
@SikoSoft 

Same here. I see almost a year ago this PR was merged https://github.com/dozoisch/react-google-recaptcha/pull/196

Seems like this is in version 3.0.0-alpha.1 and I am not sure if this is ok to use.

**Comment by Beraa995** [comment] 2022-05-11 21:15
Just an update for this topic. Using 3.0.0-alpha.1 version fixed this problem.

**Comment by 0biWanKenobi** [comment] 2022-09-16 12:55
This keeps happening, and in my case it's even worse because **the whole page freezes**. There is a function that keeps getting called _minutes_ after the badge has loaded. This is the obfuscated code, inside of recaptcha__[lang].js:

```javascript
function(Z, N, w, r, e, q, X, T, V, z) {
    return ((T = ["play", 9, 26],
    4 <= (Z << 1 & 13)) && 1 > (Z << 2 & 7) && (V = function(Y) {
        return N.next(Y)
    }
    ,
    X = function(Y) {
        return N["throw"](Y)
    }
    ,
    z = new Promise(function(Y, n) {
        function t(C) {
           // C.done often evaluates to false, so the right side is executed
           // and sometimes, randomly, the last "then" times out
            C.done ? Y(C.value) : Promise.resolve(C.value).then(V, X).then(t, n)
        }
        t(N.next())
    }
    )),
    (Z | 7) < T[2] && Z - 2 >= T[1] && (q = h[33](16, "end", null, r ? qm : XH, w),
    H[34](T[2], h[41](58, w), q, T[0], J(function() {
        U[25](50, this.V(), "overflow", "visible")
    }, w)),
    H[34](24, h[41](90, w), q, N, J(function() {
        r || U[25](35, this.V(), "overflow", ""),
        e && e()
    }, w)),
    z = q),
    (Z & 71) == Z) && (w = void 0 === w ? new Kb : w,
    N.N = w),
    z
}
```

I have added comments in the code above to show where it errors out. I hope this can somehow help fix the issue..

**Comment by mapcher** [comment] 2023-02-02 21:39
So I understood that Google Recaptcha hates to be removed and rebuilt.
Instead of creating it on selected pages of my Vue application (register, login atc.), I create it once on the application load and just make it invisible on all pages except selected with style {visibility: hidden;}
Finally, my console is free of that annoing "Uncaught (in promise) Timeout".
Thank you, everybody!

**Comment by rowan-m** [comment] 2023-02-20 12:06
Closing old issues that are not related to the PHP client code.

**Closed by rowan-m** 2023-02-20 12:06 UTC
Labels: widget

**Comment by 0biWanKenobi** [comment] 2023-02-20 13:53
Why was this closed?

**Comment by JFGHT** [comment] 2023-02-23 12:17
> Why was this closed?

Well, you have the reason just above you.

Thing is, they did not care too much even if its a 2018 problem that has affected thousands of users.

**Comment by renataleal335** [comment] 2023-10-23 19:16
Did anyone solve it? I'm facing the same problem with nuxt 3

**Comment by canavan-a** [comment] 2023-10-26 19:53
Having the same problem. 5 years later.

**Comment by KomaCrazy** [comment] 2023-11-01 12:20
Having the same problem.will 6 years

**Comment by mapcher** [comment] 2023-11-01 19:58
Newcomers here, why don't you follow my instructions https://github.com/google/recaptcha/issues/269#issuecomment-1414409419 and keep posting comments that you have the problem?

**Comment by infodusha** [comment] 2023-11-02 20:35
> Newcomers here, why don't you follow my instructions [#269 (comment)](https://github.com/google/recaptcha/issues/269#issuecomment-1414409419) and keep posting comments that you have the problem?

I guess that requires extra logic to create when using reactive frameworks

**Comment by mr-abdellah** [comment] 2023-11-15 10:01
**5 years later...problem remains** 😁🙌

**Comment by rafi-medimesh** [comment] 2023-11-28 09:01
Any update on this after more than 5 years?

**Comment by patotoma** [comment] 2023-11-28 10:54
I wouldn't be very hopeful. Please take a look at my chart where I'm showing that longer the time has passed, the amount of updates to be expected is smaller.

<img width="920" alt="chart" src="https://github.com/google/recaptcha/assets/3104587/48b3618a-c35d-4446-8e32-0993ba0b7cb6">

**Comment by UnnikrishnanBhargavakurup** [comment] 2023-12-26 18:07
I also face the same issue in React, particularly in Next.js. I resolved it by including `defer: true`, as shown below:
```
import { GoogleReCaptchaProvider, useGoogleReCaptcha } from "react-google-recaptcha-v3"
....
....
<GoogleReCaptchaProvider reCaptchaKey="my-key" scriptProps={{ async: true, defer: true }}>
  {children}
</GoogleReCaptchaProvider>
```

**Comment by dougwigg** [comment] 2024-01-30 16:46
React/Firebase 9/Web: I was seeing this error and resolved it by leaving the Recaptcha element in the DOM and using state to toggle display: block|none.  This was clunky and not Reacty but worked, it looked roughly like:

`
{ showCodeInput
  ? <CodeInput />
  :  <PhoneInput />
}
<div id="captcha" style={{display: showCodeInput ? 'none' : 'block'}} />
{ showCodeInput
  ? <SubmitCodeButton />
  :  <SubmitPhoneButton />
}
`

**Comment by kamami** [comment] 2024-01-30 23:53
Same issue in 2024, wondering why this is closed?

**Comment by mapcher** [comment] 2024-01-31 07:38
> Same issue in 2024, wondering why this is closed?

Obviously, because the solution was found. To show and hide the only captcha on the whole website instead of creating and deleting multiple captchas on every navigation between pages.

**Comment by CarlosLonghi** [comment] 2024-04-17 12:24
Based on the solution presented in the instruction:  https://github.com/google/recaptcha/issues/269#issuecomment-1414409419

I managed to solve this problem in Next.js, below is my solution: 
`
export function YourComponentName() {
  const reCaptchaSiteKey = process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY || ''

  const [captcha, setCaptcha] = useState<string | null>(null)

  return (
    <ReCAPTCHA
      sitekey={reCaptchaSiteKey}
      onChange={setCaptcha}
      hidden={captcha !== null}
    />
  )
`

**Comment by mdnelles** [comment] 2024-05-09 17:06
The error for me was almost certainly because of re-rendering.  I would see the ReCaptcha box "blink" and I knew it was going to crash.  The following solution worked for my React application.  I stopped using useState (causes a re-render) and started using useRef. (does not cause re-render)

```
const captcha = useRef<boolean>(false);

   function onChange(value: any) {
      captcha.current = !captcha.current;
      console.log("Captcha: ", captcha.current);
   }
   
   <form>
   
   <ReCAPTCHA sitekey={SITE_KEY} onChange={onChange} />
   
   </form>
   ```

**Comment by HastyCyborg** [comment] 2024-05-09 19:16
In simple words, In React, take the recaptcha container 
`<div id="recaptcha-container"></div>` (in case of some google phone validation procedure)
to the top component where it doesn't re-renders on button clicks. This worked for me.

Another fix, not the best way though, just window.location.reload() the page once main component's work is done (say you are done with signup).

**Comment by insothiry** [comment] 2024-06-13 08:38
using window.location.reload() after successfully verified worked for me

**Comment by jamieheng** [comment] 2024-06-13 08:39
> using window.location.reload() after successfully verified worked for me
thank you

**Comment by andreszs** [comment] 2024-06-14 23:37
> using window.location.reload() after successfully verified worked for me

How on earth would you implement that in the environment of the browser platform from Apache Cordova? Such workaround is not valid in this case, sorry.

**Comment by omerkaz** [comment] 2024-07-12 13:40
> So I understood that Google Recaptcha hates to be removed and rebuilt. Instead of creating it on selected pages of my Vue application (register, login atc.), I create it once on the application load and just make it invisible on all pages except selected with style {visibility: hidden;} Finally, my console is free of that annoing "Uncaught (in promise) Timeout". Thank you, everybody!

probably that's the way

**Comment by FabioZan86** [comment] 2024-09-18 15:17
curse localhost/:1 Uncaught (in promise) Timeout

**Comment by FabioZan86** [comment] 2024-09-18 22:03
After a long time to solve the problem of the `Uncaught (in promise) Timeout` error, it was time to reset before removing the captcha from dom/react/html.
```
let resetTimeout: ReturnType<typeof setTimeout> | null = null;

export const resetCaptcha = () => {
  // Clears any previous timeouts to avoid multiple resets
  if (resetTimeout) {
    clearTimeout(resetTimeout);
  }

  // Set the timeout to ensure the reset occurs after the specified time
  resetTimeout = setTimeout(() => {
    if (recaptchaRef) {
      const widgetId = recaptchaRef.getWidgetId();
      if (widgetId !== null && widgetId !== undefined) {
        recaptchaRef.reset(widgetId);
      }
    }
  }, 1000); // Waiting 1 second to avoid runtime error
};

```
in the component react:
```
  const handleCaptchaReset = () => {
    if (showCaptcha) {
      resetCaptcha();
      setCaptchaToken(null);
      setValue('captcha_resolved', false);
      setShowCaptcha(false);
    }
  };
```

**Comment by Ben-CA** [comment] 2025-01-08 22:08
Would be nice to see a proper fix from Google on this.

**Comment by rafi-medimesh** [comment] 2025-01-09 08:34
Wow, now this issue is 6 years old and old enough to start school! Maybe it’s time we give it a graduation ceremony and finally solve it? 🎓😂

**Comment by JustFly1984** [comment] 2025-07-10 09:22
switch to cloudflare turnstile or something else

**Comment by Javid-Git** [comment] 2026-01-29 07:55
> > Same issue in 2024, wondering why this is closed?
> 
> Obviously, because the solution was found. To show and hide the only captcha on the whole website instead of creating and deleting multiple captchas on every navigation between pages.

No brother, that is not a solution it is a workaround. This should be fixed or offered a proper solution as a guidline how should it work.

**Comment by FabioZan86** [comment] 2026-02-06 17:20
https://security.googlecloudcommunity.com/community-blog-42/switching-google-s-role-with-recaptcha-from-data-controller-to-data-processor-6646

**Comment by DavidIQ** [comment] 2026-02-06 17:50
> https://security.googlecloudcommunity.com/community-blog-42/switching-google-s-role-with-recaptcha-from-data-controller-to-data-processor-6646

About as relevant to this issue as apple pie...
