### ISSUE TITLE
reCaptcha seems to loop indefinitely when third party cookies are disabled

### ISSUE THREAD

**Issue by raphj** [google/recaptcha#296] opened 2019-02-06 15:42 UTC
**Issue description**

I'm one element of the gigantic set of users of the Web hindered by reCaptcha's existance. Also see issue #286. Google does not have any easy way of submitting bugs for their products as someone suffering collateral damages because of people picking them so here it is. 

reCaptcha seems to loop indefinitely when third party cookies are disabled and trackers are blocked.

**Environment**

I don't use recaptcha as a developer myself.

**Reproducing the issue**

Disable third-party cookies in your browser and try passing reCaptcha's maddening traffic lights and front stores.

Additionally, add "*.google.*" as a blocking rule in uBlock Origin (on Firefox) to be sure to reproduce my setup with high precision, and block any kind of trackers with privacy lists.

**Expected Behavior**

reCaptcha should at least tell the user to get lost when something obviously does not work as expected instead of letting them die before an endless stream of front stores and traffic lights in the cold.

**Comment by pshah123** [comment] 2019-02-14 00:20
I'm experiencing the same issue. Also, this seems to be expected behaviour, as they'll just allow me to solve 12-15 captchas before saying "Something went wrong" every single time. I'm pretty sure they're just using this as a training loop. There doesn't seem to be any workaround if you don't want to share browsing activity with Google, and surprisingly since the data they forcibly collect is not PII they're allowed to block content indefinitely/have you solve their captchas indefinitely.

I doubt you'll get a reply since @rowan-m in the other thread marked this with a pseudo-WONTFIX:

> This repo is for the client code for developer that need to verify their response to the API. I understand that the challenges can be frustrating. You might want to consider contacting the sites where you're experiencing this to advise them to update to the v3 version of the service which presents a confidence score rather than blocking with a challenge.

For what it's worth, as a web developer who would like to add captcha to my technology, it's an enormous antipattern for recaptcha to fail quietly and not provide any user feedback as to the failure so that they can adjust. This is not made clear by error messages provided either.

**Comment by grahamperrin** [comment] 2019-02-20 01:30
> … an enormous antipattern for recaptcha to fail quietly and not provide any user feedback as to the failure so that they can adjust. This is not made clear by error messages provided either.

+1

The lack of clarity can be hugely frustrating for end users and a big waste of time for support staff.

**Comment by grahamperrin** [comment] 2019-02-20 01:36
<https://github.com/google/recaptcha/issues/155#issuecomment-409589834>: 

> This isn't directly related to the PHP code which is what this repo focuses on. However, …

**Comment by vertigo220** [comment] 2019-04-11 21:39
Been posting in another issue, not directly related to this, but definitely part of the annoyance that is reCaptcha. While the cookie situation is likely partially innocent, i.e. a way to have a good idea of whether a "user" is a human or a bot, I'm convinced it's also at least partially designed to force Google cookies on systems regardless of other settings (blocking 3rd-party cookies, deleting Google cookies, etc) in order to prevent the massive time waste of having to do captchas all the time, and spend 3+ minutes on them each time. I'm also convinced they are, both in general and especially in these cases, using people to train their systems. Anyways, as discussed in the other issue, I have serious concerns about v3, and suspect it will be even worse than v2, since it will quite likely simply block people instead of offering them the ability to prove they're human (even if that does take FAR longer than it should and still often fail). And it seems to me the requirement for users to have Google cookies on their systems just to use a number of unrelated sites, not to mention the fact said cookies aren't even disclosed, is in [violation of GDPR](https://stackoverflow.com/questions/50439294/prevent-google-recaptcha-setting-a-cookie-gdpr) and possibly (though, sadly, unlikely) FTC rules.

**Comment by hellimod** [comment] 2019-10-06 15:29
I would recommend the project be canceled. This kind of poorly coded application with google sponsorship can cause real damage to the internet as a whole.

**Comment by theAntiBob** [comment] 2019-11-15 19:38
I really didn't anticipate having my (limited) time wasted by an unquestionably inappropriate neglect to ask my permission before being used to unnecessarily retrain (detrain, in my opinion) proprietary routines under the guise of humanoidal verification as an assumedly independent 3rd party service.

I seriously doubt the quality of data being collected on frustrated and confused (unwitting unwilling and unconsenting) users could be useful for anything other than anticipating patience loss thresholds. Nice work, gladOS.

Comments like:
"...waste of time for support staff"
"aren't even disclosed, is in violation of GDPR and possibly (though, sadly, unlikely) FTC rules"
and "poorly coded application with google sponsorship can cause real damage to the internet as a whole"
are incredibly valid with this type of violation of trust and are, unfortunately, too rarely voiced by the supposed "consentee"

due to an obvious gap in the current levels of technical capability posessed by end users, a clear and valid disclaimer is obviously needed to avoid having the term "intentional misleading" be so applicable to this behavior as well.

**Comment by danhash** [comment] 2020-01-15 16:41
When trying to log in to JimmyJohns.com, which uses reCAPTCHA, with third-party cookies disabled in Firefox, clicking Login does nothing. As soon as I enable third-party cookies, clicking Login works. I've already reported this issue to Jimmy John's, who will likely do nothing, but the real culprit is Google's reCAPTCHA requiring third-party cookies. This dependency needs to be removed.

**Comment by efimBistrov** [comment] 2020-10-29 12:25
When will be this bug fixed?

**Comment by grahamperrin** [comment] 2020-12-27 00:42
### Firefox

If I recall correctly, there's no problem with enhanced tracking protection at its _Standard_ level. 

Don't prefer the _Strict_ level unless you're prepared to deal with some breakage; this may include reCaptcha functionality. 

There's a forewarning: 

![image](https://user-images.githubusercontent.com/192271/103161564-cd0e9300-47b1-11eb-8b00-72f393f9a32e.png)

(I do prefer the strictness.)

**Comment by raphj** [comment] 2020-12-27 21:33
Strict privacy / anti-tracking settings should not prevent people from accessing websites, especially because of a CAPTCHA technology. Telling computers and humans apart certainly does not require tracking.

**Comment by dylanjamesdev** [comment] 2021-08-13 23:28
Bumping because this is still a issue, the recaptcha keeps cycling no matter what browser or user does it. It will not allow anyone to pass it.

**Comment by snex** [comment] 2022-10-15 18:45
Google: Don't be evil

Also Google: Disable all privacy settings or we will put you in an infinite captcha loop.

Captcha is supposed to tell humans apart from bots. If I solved it the first time, you know I'm a human. Stop infinite redirecting me. You are violating your own terms of service.

**Comment by vertigo220** [comment] 2022-10-15 21:09
> Google: Don't be evil
> 
> Also Google: Disable all privacy settings or we will put you in an infinite captcha loop.
> 
> Captcha is supposed to tell humans apart from bots. If I solved it the first time, you know I'm a human. Stop infinite redirecting me. You are violating your own terms of service.

They removed the don't be evil bit a few years ago. At least they finally showed a bit of honesty when they did that.

**Comment by grahamperrin** [comment] 2022-10-15 23:47
Stop boring me with infinite complaints. Click the picture of the bicycle.

**Comment by snex** [comment] 2022-10-15 23:51
> Stop boring me with infinite complaints. Click the picture of the bicycle.

I sure hope you aren't a Google representative because if you are, your lack of reading comprehension is exactly why your software is turning to hot garbage.

It doesn't matter how many times the bicycle is clicked, the page just redirects back to itself. Now stop wasting the inflated 6 figure salary they pay you on diversity initiatives and go fix it.

**Comment by grahamperrin** [comment] 2022-10-15 23:56
> I sure hope you aren't a Google representative 

I'm not. 

> It doesn't matter how many times the bicycle is clicked, 

> Now stop wasting the inflated 6 figure salary they pay you 

First, pay me that salary

> on diversity initiatives 

then I can make a massive charitable donation to Bicycles for The Bored™, which will, eventually, increase the number of bicycles photographed for captcha purposes, ultimately making for a more pleasant experience when a fix occurs. 

> and go fix it.

No, and you're welcome.

**Comment by snex** [comment] 2022-10-16 00:13
What on earth are you even talking about? The issue is not "bicycles keep appearing no matter how many I click."

The issue is "I clicked all the bicycles and submitted the page successfully, and then it just went to another captcha page."

If you aren't even a maintainer of the project, why are you commenting at all? You have contributed absolutely nothing.

**Comment by grahamperrin** [comment] 2022-10-16 00:29
> why are you commenting at all?

Please ask yourself whether https://github.com/google/recaptcha/issues/296#issuecomment-1279806239 helped to progress the issue.

**Comment by snex** [comment] 2022-10-16 01:04
> > why are you commenting at all?
> 
> Please ask yourself whether [#296 (comment)](https://github.com/google/recaptcha/issues/296#issuecomment-1279806239) helped to progress the issue.

The comment before mine is over a year old. I know you guys just hope people will give up and go away, so you can close the issue and boost your KPIs and collect that sweet bonus money, but unfortunately the issue is still happening as of October 15, 2022. You probably could have fixed it in the time you wasted being snarky to your customers.

**Comment by grahamperrin** [comment] 2022-10-16 01:14
> I know you guys just hope people will give up and go away,

Wrong. 

I hope for a fix relating to a technology that's intended to deter spam and other unwelcome noise. 

If you didn't want responses to your noise about the supposed evils of Google, then why did you make the noise? I'll now hide my responses; please consider doing the same.

**Comment by cyril-nmpro** [comment] 2023-02-04 06:20
And the issue is still happening in Feb 2023

**Comment by mooleshacat** [comment] 2023-02-16 19:18
Yep can't use any website that uses reCaptcha which is basically 99% of the internet. Also I refuse to accept that "disable ad block" and "disable VPN" are the proper solution - it's only gaslighting and blaming users for protecting their privacy and their personal data from three letter agencies who work directly with Google.

If the answer to be able to use a website is to allow Google to track you, that is the wrong answer.

Google made it so difficult that actual humans can't pass their "turing test".

Time for a new idea, or at the very least a complete re-code of reCaptcha.

I also think its time for a class action lawsuit against Google, Alphabet, et al.

**Comment by rowan-m** [comment] 2023-02-20 12:04
Closing old issues that are not related to the PHP client code.

**Closed by rowan-m** 2023-02-20 12:04 UTC
Labels: service discussion

**Comment by raphj** [comment] 2023-02-20 12:06
@rowan-m Fair enough, can you make sure transmit the issue to the reCAPTCHA team please?

**Comment by vertigo220** [comment] 2023-02-20 14:12
> Closing old issues that are not related to the PHP client code.

This is an issue about recaptcha posted under the recaptcha repo. How is it not related?

**Comment by SedatedJdawg** [comment] 2024-07-02 07:49
July 2nd 2024 and I'm still dealing with infinite captcha loop... I've just decided some parts of the internet will be inaccessible!

**Comment by kiddailey** [comment] 2024-08-27 21:25
August 27, 2024 and I can't use VirusTotal in any browser anymore on Windows because of reCaptcha loops -- even when I disable all blocking and disable privacy protections.  Tried in Firefox, Chrome, Edge, and Vivaldi with no luck.

However, I don't get ANY reCaptcha prompts when using Firefox, Vivaldi and Safari on MacOS with strict privacy protections turned on!

**Comment by Biep** [comment] 2025-03-10 22:46
Still persisting.  And I can't report it to the sites using ReCaptcha, because to log an issue - I must solve a ReCaptcha.
