### ISSUE TITLE
There is no error code in Response when success is false

### ISSUE THREAD

**Issue by iroy2000** [google/recaptcha#111] opened 2016-07-01 01:18 UTC
I'm using VERSION = 'php_1.1.2'  of this library

I'm trying to debug why my recaptcha doesn't work,  and try to debug from the source and here is the response from the object.

array(3) {
  ["success"]=>
  bool(false)
  ["challenge_ts"]=>
  string(20) "2016-07-01T00:08:10Z"
  ["hostname"]=>
  string(16) "my_host_name_here"
}

And when I try to use the request in postman, still get the same response, I'm new to it, and any help will be appreciated.  Currently I know it is not success, but there is no "error" code

![screen shot 2016-06-30 at 6 14 40 pm](https://cloud.githubusercontent.com/assets/487520/16509128/c24aa402-3eee-11e6-81ed-a80928e60ec5.png)

I always get success : false response  ( with no error code ) even if the captcha matches on the page.  Is there something I did wrong here?  Any help is appreciated.

**Comment by odorisioe** [comment] 2016-07-07 00:21
Same problem.
I receive "success: false" since the first verify attempt.
Did you find the reason?

**Comment by cmanley** [comment] 2016-07-13 22:20
Same here. I now treat "success: false" without error codes as success because too many form posts are being rejected because of this bug.

**Comment by jasonfedor** [comment] 2016-07-13 22:44
Error codes are optional, and only are sent if there is an input error. Success:false without an error code means that the response itself was bad for some reason (timeout, duplicate of previous submitted response, etc.)

**Comment by petrabarus** [comment] 2016-08-19 09:16
> I always get success : false response ( with no error code ) even if the captcha matches on the page. Is there something I did wrong here? Any help is appreciated.

I also got the same problem here.

**Comment by ronjunelopez** [comment] 2016-12-14 06:01
I also encountered the same issue. Is there a fix here? or we should assume this is normal?

**Comment by lefevrejeremy** [comment] 2017-03-21 15:31
any update? I got the same issue!

**Comment by masimao** [comment] 2017-04-01 23:36
I am debugging and testing, so i got this issue when i sent the same POST more than one time, as @jasonfedor said. To prevent an empty error to the user, i am sending a custom message always i get `success => false`.

But it would be very good if a specific error was returned as the method name says: `getErrorCodes()`.

**Comment by jckhan** [comment] 2017-04-06 19:47
Same problem here , I´m doing a GET request via postman or soapui , i get success = true for a valid secret and response for the domain localhost , but when I change the domain I get always success =  false without a error code .

**Comment by mpavel** [comment] 2017-04-28 06:30
We are also encountering the same issue. About 10% of our submissions are getting a `success: false` with no error codes, making it very hard to identify the problem our users have.

We have tried to replicate the issue without any success.

As far as I've seen, if a recaptcha response code is being used the second time, the response will say `success: false` without error codes. If I manually try to verify a recaptcha code, but I type in "asdf" it will tell me:

```
{
  "success": false,
  "error-codes": [
    "invalid-input-response"
  ]
}
```

**Comment by Deseao** [comment] 2017-04-28 20:06
Is recaptcha just broken then? I keep getting these `success: false` responses, even when making the requests through postman.

**Comment by vgolubeva** [comment] 2018-04-03 16:35
I had the same problem on localhost. In my case problem was in SSL sertificate (I undestood it when I tried to use `curl_exec` for sending data and got a look at `var_dump(curl_error($ch))`). After downloading `cacert.pem` and configuring `php.ini` the issue was resolved!

**Comment by rowan-m** [comment] 2018-07-31 20:37
I'm updating the `v1.2` branch to include some additional error codes. Is there an example of this out in the wild or any additional configuration I could see to try and diagnose this?

**Closed** 2018-08-01 13:57 UTC
Labels: php, question

**Comment by Haripriya-1212** [comment] 2024-02-19 00:54
I am getting the same error - {success: false, error: null}.
Any solution?
